<a href="https://colab.research.google.com/github/darlaabril/Taller-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy




In [39]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


Numpy y sus aplicaciones

In [2]:
#Una diferencia importante entre NumPy y List es que NumPy es más rapida de leer
#Algunas aplicaciones de NumPy son las Funciones matemáticas y manejo de arrays

Instalar Numpy


In [40]:
#No se olviden instalar Numpy antes de usarlo
#Instalación:
import numpy as np
import sys

Creación de arrays, forma, tamaño y tipo de data

In [ ]:
np.array([2,4,8], dtype="int")

In [41]:
#Creación de array
a=np.array([2,4,8], dtype="int")
print(a)

[2 4 8]


In [43]:
b=np.array([[3,6,9],[1,3,5]])
print(b)

[[3 6 9]
 [1 3 5]]


In [44]:
#Ver la dimensión
b.ndim

2

In [46]:
#Ver la forma
b.shape

(2, 3)

In [48]:
#Ver el tipo de data, int16 para valores no tan grandes
#Es eficiente especificarlo
a.dtype

dtype('int64')

In [47]:
b.dtype

dtype('int64')

In [49]:
#Ver el tamaño (bytes)
a.itemsize

8

Acceder/cambiar elementos específicos, filas, columnas, etc

In [51]:
a=np.array ([ [1,3,5,7,9,11,13 ],[ 2,4,6,8,10,12,14]])
print(a)

[[ 1  3  5  7  9 11 13]
 [ 2  4  6  8 10 12 14]]


In [52]:
 #Elemento especifico [fila, columna]
 a[1,5]

12

In [53]:
#Fila
a[ 0,:]

array([ 1,  3,  5,  7,  9, 11, 13])

In [54]:
#Columna
a[:,2 ]

array([5, 6])

In [55]:
#Cambiar data
a[1,5]=40
print(a)

[[ 1  3  5  7  9 11 13]
 [ 2  4  6  8 10 40 14]]


In [57]:
b=np.array([[[ 2,4], [ 6,8]], [ [10,12 ],[ 14,16]]])
print(b)

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


In [58]:
#[matriz, fila, columna]
b[0,1,1]

8

In [59]:
#Obtener un elemento específico fuera del array
#en el siguiente ej no especificamos cual de las 2 matrices por lo que obtendremos 2 filas
b[:,1,:]

array([[ 6,  8],
       [14, 16]])

In [60]:
#reemplazo 
b[:,1,:]= [[1,1],[2,2]]
print(b)

[[[ 2  4]
  [ 1  1]]

 [[10 12]
  [ 2  2]]]


Inicialización

In [61]:
#Matriz de 0's
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
#Matriz de 1's
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [64]:
#Matriz de n's
np.full((2,3),13)

array([[13, 13, 13],
       [13, 13, 13]])

In [65]:
a

array([[ 1,  3,  5,  7,  9, 11, 13],
       [ 2,  4,  6,  8, 10, 40, 14]])

In [66]:
#Matriz con x forma
np.full_like(a,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [67]:
np.full_like(b,5)

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [68]:
#Numeros decimales aleatorios
np.random.rand(3,4)

array([[0.1522039 , 0.48925822, 0.57305135, 0.46545766],
       [0.32119646, 0.29417561, 0.45911629, 0.34741151],
       [0.38067481, 0.56364814, 0.16298971, 0.03292756]])

In [69]:
#Numeros decimales aleatorios como a
np.random.random_sample(a.shape)

array([[0.76330741, 0.93482329, 0.41208791, 0.26985535, 0.7799463 ,
        0.93677838, 0.78379883],
       [0.87230199, 0.88214057, 0.34415626, 0.72235742, 0.02564074,
        0.84442763, 0.04285666]])

In [70]:
#Numeros enteros aleatorios (Startvalue, shape)
np.random.randint(1,9,size=(3,3))

array([[2, 1, 4],
       [2, 2, 5],
       [1, 4, 2]])

In [71]:
#Matriz de identidad
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
arr=np.array([[2,4,6]])
arr

array([[2, 4, 6]])

In [73]:
#Repetir un array
arr=np.array([[2,4,6]])
rl=np.repeat(arr,3,axis=0)
print(rl)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [74]:
r2=np.repeat(arr,3,axis=1)
print(r2)

[[2 2 2 4 4 4 6 6 6]]


In [75]:
#Modificar array
x=np.array([2, 4, 6])
y=x
y[0]=40
print(x)

[40  4  6]


Matemática básica

In [76]:
a=np.array([40, 4,  6])
print(a)

[40  4  6]


In [77]:
a+2

array([42,  6,  8])

In [78]:
a-2

array([38,  2,  4])

In [79]:
a*2

array([80,  8, 12])

In [80]:
a/2

array([20.,  2.,  3.])

In [82]:
b=np.array([10,  2,  3])
c = a+b

In [83]:
c

array([50,  6,  9])

Reorganizar matrices

In [84]:
#Apilar vectores: forma vertical
v1=np.array([1,  2,  3])
v2=np.array([4,5,6])
np.vstack([v1,v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
#Apilar vectores: forma horizontal
h1=np.array([1,  2,  3])
h2=np.array([4,5,6])
np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6])